### ISSUE TITLE
Remove `neuron rib` server commands

### ISSUE THREAD

**Issue by fiatjaf** [fiatjaf/neuron.vim#13]
I don't use these things and to me it feels very weird to run a server from inside vim. Am I crazy? Do people use it?

If there's even one person using this feature then I won't remove it.

**Comment by srid** [comment]
Typically, if I'm using nvim to edit zettels, I start `tmux`, with a split pane -- the left running `neuron rib -w`, and the right (larger panel) running nvim.

**Comment by fiatjaf** [comment]
That's what I'm doing here too!

**Comment by wheelsandmetal** [comment]
I also don't use it

Just my 2cents though

**Comment by fenetikm** [comment]
yeah, let's remove it.

**Comment by fenetikm** [comment]
...and they are now gone.
