### ISSUE TITLE
Tag functionality: add new, search by tag

### ISSUE THREAD

**Issue by fenetikm** [fiatjaf/neuron.vim#15]
Just having a look at: https://github.com/felko/neuron-mode - would be great to add in some tag handling stuff such as `add tag/s`, maybe `edit tags` too.

Again, I could work on this if you want? Thoughts?

I think `add tag` would ask you to enter a tag, which would then add it to the yaml. Edit tags would jump you up to tags in the yaml. If the tags section in the yaml doesn't exist, both functions would add it in.

**Comment by fiatjaf** [comment]
Yes, this is a good feature. I was thinking we should have some kind of tag management initially, but then forgot about it.

I think we could use the same `gzz/gzi` fzf-powered screen to insert tags based on tags that already exist.

**Comment by fenetikm** [comment]
yeah, something where you could do a search by tag would be on the list too. Will get going on it this week.

**Comment by fenetikm** [comment]
Got a work in progress here: https://github.com/fiatjaf/neuron.vim/pull/18

**Comment by fenetikm** [comment]
Have created a `tag-support` branch with my work on this in there. Think I will split it up into different issues so that you can get the functionality earlier as it is created vs all at once.

**Comment by fenetikm** [comment]
This has now been merged in as part of that latest merge: https://github.com/fiatjaf/neuron.vim/pull/34
