### ISSUE TITLE
Windows LNK issue

### ISSUE THREAD

**Issue by beefeater7** [fiatjaf/neuron.vim#16]
*nix tools on Windows like to be a hassle. Maybe I've been trying to push the square peg through the round hole, but I thought I'd report my findings. 

First, I followed the instructions to use neuron [through Ubuntu WSL2](https://neuron.zettel.page/install.html). Next...

`C:\WINDOWS\system32\wsl.exe /home/me/.nix-profile/bin/neuron`

This is the **'Target'** address I put in my neuron.lnk shortcut on the PATH. It's important to keep the **'Start in'** field empty.

It works great for using the program in cmd. `:!neuron` also works fine in nvim.
![image](https://user-images.githubusercontent.com/10468970/93938210-343b2800-fd29-11ea-89c6-366f60fb3ee9.png)

However. 
![image](https://user-images.githubusercontent.com/10468970/93937340-e114a580-fd27-11ea-92bb-ca2115752967.png)

The plugin seems to have an issue with this solution. Any idea why?

**Comment by fiatjaf** [comment]
I don't know, but I would try running `echo system('neuron new')` and then `echo system('<your-executable-path-here> new')` and see what happens.

**Comment by beefeater7** [comment]
Those commands do work:

![image](https://user-images.githubusercontent.com/10468970/93943109-1f16c700-fd32-11ea-9bd9-d724a0e868dd.png)

Same goes for `gzn`; it triggers no error and opens the note. The others trigger a variation of errors, I could document them if you want.

```
let g:neuron_executable="neuron"
let g:neuron_executable="neuron.lnk"
let g:neuron_executable="C:/cmd-line-utilities/neuron"
```

These are variations of my path setting. All give the same error, above (capital extension aside).

**Comment by fiatjaf** [comment]
Ok, it seems to be an issue with `jobstart`/`job_start`. The same thing happens in `vim` and `nvim`?

This is from the `jobstart` nvim docs:

> NOTE: on Windows if {cmd} is a List:
>   - cmd[0] must be an executable (not a "built-in"). If it is in $PATH it can be called by name, without an extension:
>   `:call jobstart(['ping', 'neovim.io'])`
>   If it is a full or partial path, extension is required:
>   `:call jobstart(['System32\ping.exe', 'neovim.io'])`
>   - {cmd} is collapsed to a string of quoted args as expected by CommandLineToArgvW https://msdn.microsoft.com/bb776391 unless cmd[0] is some form of "cmd.exe".

Do you understand something from it?
Maybe I should just not use a `List`?

**Comment by fiatjaf** [comment]
Ok, let's do it with a string, I don't know why it was a list anyway. Please let me know if it solved the issue.

**Comment by beefeater7** [comment]
That fixes it. Thanks a ton!

![image](https://user-images.githubusercontent.com/10468970/93951426-948c9280-fd46-11ea-8433-58e9dea59e88.png)
