### ISSUE TITLE
 Handle exception error when insert invalid link?

### ISSUE THREAD

**Issue by bangedorrunt** [fiatjaf/neuron.vim#20]
Hi,

It took me a while to realize where this error came from

<img width="1489" alt="Screen Shot 2020-09-29 at 3 52 32 pm" src="https://user-images.githubusercontent.com/1514823/94517760-f891e800-026b-11eb-8ab1-697363b3c961.png">

I happened to have an _[[invalid link]]_ inside a very old note which make Neuron raise an exception. Could you please handle this case for better meaningful error such as _"Invalid link has been found at {Zetter Title}"_ rather than above encrypted exception error?

**Comment by fiatjaf** [comment]
Does this happen when you go to `[[invalid link]]` and press `gzo`?

**Comment by bangedorrunt** [comment]
> Does this happen when you go to `[[invalid link]]` and press `gzo`?

Yes, and also when I do `gzr` to force Neuron refresh cache.

**Comment by fenetikm** [comment]
I'll have a look at this.

**Comment by fenetikm** [comment]
I believe this should now be fixed in https://github.com/fiatjaf/neuron.vim/pull/33
