### ISSUE TITLE
Neuron executable not found / No virtual text

### ISSUE THREAD

**Issue by vcavallo** [fiatjaf/neuron.vim#22]
Hello. So far I'm loving this fork in `vim`. But in `nvim` I'm having the following issue:

When opening any zettel file I get `neuron executable not found!` in the status bar.
I also don't see any virtual text, but I assume it may be because `neuron.vim` can't find the `neuron` backend it likely requires.

nvim version: 0.4.4
neuron version: 1.0.0.0
If I run `:!neuron --version` from _within_ neovim, it does locate the command properly.

As I said, this only happens in `nvim`, which I'm fairly new to. Perhaps I have neovim misconfigured?

Update:

I've tried adding: `let g:path_neuron = "/home/vcavallo/.nix-profile/bin/neuron"` to my vimrc but the problem remains

**Comment by vcavallo** [comment]
As suspected, this was a result of my not having `nvim` configured properly :facepalm: 

For posterity: if you switch from vim to neovim, make sure your plugins are actually installing to the right place in neovim!

**Comment by lambtho12** [comment]
> make sure your plugins are actually installing to the right place in neovim
Could you be more specific ?

I am facing this same issue. I install my plugins in `.local/share/nvim/plugins/` and never had any issue so far. What should I do to make it find neuron?
