### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by wbadart** [fiatjaf/neuron.vim#28]
Hey team-

I use `home-manager` to manage my neovim plugins, so it would be super convenient to be able to grab neuron.vim from nixpkgs. I see that the original neuron.vim has [an entry] in `pkgs.vimPlugins`, so hopefully that's a good starting point.

I'm happy to tackle this on my own, but I'm still pretty new to nix (and to nixpkgs governance) so I thought I'd post this here in case someone a little more seasoned has a quick fix.

Many thanks!

[an entry]: https://search.nixos.org/packages?show=vimPlugins.neuron-vim&query=vimPlugins.neuron&channel=unstable

**Comment by fiatjaf** [comment]
Please do it, I have no idea of how this works! You're probably the most qualified person since you are interested!

**Comment by wbadart** [comment]
Did some quick research, looks like it's actually pretty straight-forward: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#adding-new-plugins-to-nixpkgs

Currently having trouble with that `update.py` script; I'll try from another machine this evening.

**Comment by wbadart** [comment]
See NixOS/nixpkgs#101385

**Comment by wbadart** [comment]
Finally got that PR merged! Not sure what the delay typically is, but we should be landing on nixpkgs-unstable imminently 🎉

**Comment by fiatjaf** [comment]
Giant review process they have there!

Should we add a note on the README here saying it's possible to install it from nixpkgs somehow? Please open a PR if you feel like doing it!

**Comment by wbadart** [comment]
You got it 👍 I'll make that note as soon as I can do a successful installation via nix (might be a few days).
