### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by fenetikm** [fiatjaf/neuron.vim#4]
If I enable the plugin and start neovim inside of a `~` directory without specifying a file then it hangs.

It seems to be due to trying to go up the directories until it hits "/" (in `ftdetect/neuron.vim) but I think what is happening is:
- s:current is blank (no file)
- s:dir ends up as `.` (current directory)

and so it keeps trying to go up the tree when there is none.

**Comment by fiatjaf** [comment]
Good catch.

Now I'm not sure if I try to fix this or remove it entirely and just search for the current directory now that neuron has [changed its policy](https://github.com/srid/neuron/issues/389).
