### ISSUE TITLE
Neovim startup shows error after backlink update

### ISSUE THREAD

**Issue by beandipper** [fiatjaf/neuron.vim#47]
After resolving #45 I just noticed that starting up my vim shows an error in the refresh_callback_nvim function. The below image is of the error. Functionality of the plugin seems to otherwise be fine from what I can tell.

![image](https://user-images.githubusercontent.com/397080/98936990-be7d5c80-2520-11eb-909a-2e48b45d5ab6.png)

**Comment by hazelweakly** [comment]
I was able to do something like this as a hacky workaround, but I'm not sure if it's actually correct in any meaningful way:

```diff
diff --git a/autoload/neuron.vim b/autoload/neuron.vim
index 329c4f7..e0ec2fa 100644
--- a/autoload/neuron.vim
+++ b/autoload/neuron.vim
 func! neuron#edit_zettel_select()
@@ -311,8 +312,16 @@ func! s:refresh_cache_callback(data)
 		if !empty(z['zettelQueries'])
 			for l in z['zettelQueries']
 				let l:key = l[0][1][0]
-				if has_key(g:_neuron_backlinks, l:key)
-					call add(g:_neuron_backlinks[l[0][1][0]], z['zettelID'])
+				if type(l:key) == v:t_string
+					if has_key(g:_neuron_backlinks, l:key)
+						call add(g:_neuron_backlinks[l[0][1][0]], z['zettelID'])
+					endif
+				elseif type(l:key) == v:t_list
+					for keyidx in l:key
+						if has_key(g:_neuron_backlinks, keyidx)
+							call add(g:_neuron_backlinks[l[0][1][0]], z['zettelID'])
+						endif
+					endfor
 				endif
 			endfor
 		endif
```

(what I saw happening was that tags were coming back in the query somehow as a list)

**Comment by beandipper** [comment]
I am also unfamiliar with vim scripting so I am unable to tell you if your patch appropriately addresses the underlying cause. 
It looks like I'm not the only one who has experienced this problem though. Did you first see it recently after the previous missing backlinks commit #45 or was it from earlier? In any case, it doesn't seem like desirable behavior(bug).

**Comment by fenetikm** [comment]
hi @beandipper - I'm not seeing that issue so my guess is that it is particular to your zettelkasten. I have added a debug var `g:neuron_debug_enable` which when set will save the last query to `query.json`. 

Could you please pull the latest version of the plugin, put `let g:neuron_debug_enable=1` in your config then open your zettelkasten and post the `query.json` file here?

**Comment by beandipper** [comment]
it could be that it is an issue with my environment yest. Because I was trying to setup my system, it could be that something particular to my zettelkasten or environment was causing the problem. I am unable to test the debug var you added because I am starting from scratch to make sure that everything is clean. 

Unfortunately by trying to install everything cleanly, I ran into another problem that I may need to leave in a separate issue. I can no longer install neuron.vim at all. I am trying to install via nixpks home-manager, but am getting an error that the g:neuron_dir variable isn't set. I don't understand vim plugins well, but it appears that there at least needs to be a default set at installation time for the plugin to install via nix. This can of course be overridden later, but it seems like it is unset by default. 

I saw that @wbadart set the plugin up to work with nix, maybe he can help. Let me know if I should move this into a separate issue.

As soon as I can get the plugin installed I will check the debug method you recommended and update this ticket.

Edit: created separate issue in #50

**Comment by fenetikm** [comment]
Hi @beandipper - yes, if you could please open a separate issue regarding the nix issue and then we can see if this one is still a problem. Thanks.

**Comment by jackhanslope** [comment]
Hi, @fenetikm. Seems to me like this might be an issue with link queries (https://neuron.zettel.page/link-query.html). I am experiencing this bug myself and removing all link queries from my zettelkasten solved it. 

As another test, I cloned https://github.com/srid/alien-psychology (the example zettelkasten used on neuron.zettel.page for link queries). Opening a zettel threw the same error as experienced here. Removing all of the link queries solved the issue. 

Hope this can be helpful!

**Comment by fenetikm** [comment]
Ok great, thanks. I'll take a look using the example zettelkasten.
... and yep if I add a link query to a zettel the error is thrown. Shall sort it out.

**Comment by fenetikm** [comment]
Ok, have now added in a check around the type of links that are cached. It made the error I saw go away hopefully it fixes your issue too 😄

**Comment by fenetikm** [comment]
ok, closing this. If it pops up again please re-open.
