### ISSUE TITLE
Polluting global namespace

### ISSUE THREAD

**Issue by MaienM** [fiatjaf/neuron.vim#5]
This plugin uses quite a few global variables with pretty generic names (e.g. `g:fzf_options`, `g:history`, `g:last_file`) that could easily conflict with variables used by other plugins or by people in their own functions/scripts. Some of these are for options (should be set/accessed by user), but most are internal and should not be touched by the end user.

I propose config variables are prefixed with `neuron_` (e.g. `g:fzf_options` becomes `g:neuron_fzf_options`). This is a pretty common pattern for the configuration of a plugin, and it makes it immediately obvious what plugin these options belong to. This would be a breaking change, but considering this fork only _just_ became it's own thing this seems like a good moment for it.

For the variables that aren't meant to be touched by the user I propose most of them are moved to the `s:` scope (e.g. `g:history` becomes `s:history`) if possible. For the ones that need to be used by multiple scripts the variable should be prefixed with something neuron specific to avoid collisions. I propose `_neuron_`, with the extra leading underscore to clearly differentiate it from config variables (e.g. `g:must_refresh_on_write` becomes `g:_neuron_must_refresh_on_write`).

**Comment by fiatjaf** [comment]
Agreed. Sorry, I'm new to this plugin development thing.

**Comment by fiatjaf** [comment]
Is the `s:` scope preserved accross buffer changes and so on?

**Comment by MaienM** [comment]
Yeah, a variable in the `s:` scope is preserved across buffer changes. The only variables that are specific to a buffer are those in the `b:` scope, the rest is buffer-independent.

**Comment by fiatjaf** [comment]
Thank you.

I was thinking it was something like a hierarchy of scopes: `g:` > `w:` > `b:` > `s:`
