### ISSUE TITLE
Home-Manager Nix install fails

### ISSUE THREAD

**Issue by beandipper** [fiatjaf/neuron.vim#50]
As mentioned in  https://github.com/fiatjaf/neuron.vim/issues/47#issuecomment-728702095_ , nix install fails when trying to install the vim plugin. Steps to reproduce
1. Add the plugin to home-manager
```
{ config, lib, pkgs, ... }:
let
  plugins = pkgs.vimPlugins;
  myVimPlugins = with plugins; [
    fzfWrapper
    fzf-vim
    neuron-vim
  ];
in
  {
    programs.neovim = {
      enable       = true;
      plugins      = myVimPlugins;
    };
  }
```
2. Run % home-manager switch to install

This results in the following error
```
Error detected while processing /nix/store/dx1va7x8856kw8dnx1y6xprxamsg83ba-vimplugin-neuron-vim-2020-10-29/share/vim-plugins/neuron-vim/plugin/neuron.vim:
line   66:
E121: Undefined variable: g:neuron_dir
E116: Invalid arguments for function filereadable
E15: Invalid expression: filereadable(g:neuron_dir."neuron.dhall")
remote/host: generated rplugin manifest: /nix/store/016na3sirjhj4iisg54c0yd4l28sdrrr-neovim-0.4.4/rplugin.vim
Generating rplugin.vim failed!
builder for '/nix/store/84wqqx84g4p1knm7s587l54z0w4ig7hv-neovim-0.4.4.drv' failed with exit code 1
cannot build derivation '/nix/store/ypnc90vhcxw0dlyxcv12ybac511723bp-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/paky0b068vfd2a66zzk8cc32ndj7ddsj-neovim-0.4.4-fish-completions.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/22rf12j1k9qpn561fcz3xj4mf5646khd-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/22rf12j1k9qpn561fcz3xj4mf5646khd-home-manager-generation.drv' failed
```

- Maybe we need to define the default ``neuron_dir`` value to the current directory which is standard in the neuron project(see https://github.com/fiatjaf/neuron.vim/commit/4a0ab55eb5545c5638d4b3f458e7551d3980831d). This value can then be overridden in a users vimrc if needed. 
- Setting the neuron_dir in the vim rc doesn't help with `` let g:neuron_dir="/home/<user-name>/zettelkasten/" ``

**Comment by beandipper** [comment]
It seems the ``neuron_dir`` variable is set, but nix installs doesn't have access to that location in ``ftdetect/neuron.dir`` and so it fails. I made the minor change was able to get it working again in #51. If that pull request is merged we could close this issue

**Comment by fenetikm** [comment]
Sounds good to me - will check the PR.

**Comment by fenetikm** [comment]
PR merged - see if that fixes the nix issue.

**Comment by beandipper** [comment]
fixed thanks!
