### ISSUE TITLE
ftdetect is not actually setting the path

### ISSUE THREAD

**Issue by MaienM** [fiatjaf/neuron.vim#6]
There is a loop in the ftdetect file that attempts to determine the zettelkasten root by looking for `neuron.dhall`. The result of this loop is never used though, and the autocommands are still based on `g:zkdir`, which seems odd.

**Comment by fiatjaf** [comment]
The loop assigns to `g:zkdir`, therefore it is not useless. See https://github.com/fiatjaf/neuron.vim/blob/f077f130c67b7d1838b18eb5eb787252869fc802/ftdetect/neuron.vim#L9.

**Comment by fiatjaf** [comment]
Anyway, I think I should remove that entire block anyway, see https://github.com/fiatjaf/neuron.vim/issues/4#issuecomment-692763441

**Comment by MaienM** [comment]
Ah, I misread that line, my bad. Sorry for the noise.
