### ISSUE TITLE
Editing with `neuron search -e` doesn't fill the cache

### ISSUE THREAD

**Issue by fiatjaf** [fiatjaf/neuron.vim#7]
I have no idea why.

**Comment by fiatjaf** [comment]
Why?

**Comment by fenetikm** [comment]
I'll have a look at this...

**Comment by fenetikm** [comment]
When you say "doesn't start the plugin" could you please elaborate? Seems to be loaded for me. Could you please give me some steps to reproduce?
I do:
- neuron search -e
- select a zettel
- opens vim (neovim in my case)
- `gzn` and it creates a new zettel

**Comment by fiatjaf** [comment]
Oh, I hadn't tried `gzn`. Indeed it works, so my assumption was wrong.

The issue is that `gzz` for example, doesn't work. The cache never gets filled. Other commands that use the cache also fail.

**Comment by fenetikm** [comment]
ok thanks, will check that out.

**Comment by fenetikm** [comment]
https://github.com/fiatjaf/neuron.vim/pull/17

**Comment by fenetikm** [comment]
Think this is sorted now.
