### ISSUE TITLE
Why so many files?

### ISSUE THREAD

**Issue by fiatjaf** [fiatjaf/neuron.vim#8]
I never did a Vim plugin so I have no idea why we have an `ftdetect/`, a `plugin/` and an `autoload/` directories. I would like to have a single file or perhaps two, definitely a single directory, this structure is confusing me, is it needed?

**Comment by MaienM** [comment]
It's the standard plugin structure for (neo)vim. Vim treats these different folders in specific ways, so just throwing all the code into a single file would not have the same effect. See `:help ftdetect`, `:help autoload`.

**Comment by MaienM** [comment]
Learn vim the hard way also has [a good overview](https://learnvimscriptthehardway.stevelosh.com/chapters/42.html) of the different folders and their purpose.

**Comment by fiatjaf** [comment]
Thank you, that's good stuff.
