### ISSUE TITLE
A good way to show backlinks

### ISSUE THREAD

**Issue by fiatjaf** [fiatjaf/neuron.vim#9]
I'm looking for.

**Comment by fenetikm** [comment]
I'm thinking something like https://github.com/preservim/tagbar. It would show up in it's own buffer. Would be happy to work on that myself if you want a hand @fiatjaf 

Also see the side bar on the obsidian app that has backlinks. Same kind of thing. https://obsidian.md/

**Comment by fiatjaf** [comment]
I think that would be great and specially good if you worked on it yourself because I don't feel I'm capable.

I have some questions, though:

Isn't an overkill to have a buffer always there showing backlinks when most of the times we don't really need to see backlinks? Wouldn't it take too much space? Perhaps it should be shown if the vim window was smaller than x, or maybe it could be toggleable?

**Comment by fenetikm** [comment]
Yeah it would be available via a command e.g. `:NeuronBacklinks` Could have a couple versions to open it up in a vertical or horizontal split, which is a relatively usual way to go. I'll have a go at implementing it and posting a PR.

**Comment by fenetikm** [comment]
https://github.com/fiatjaf/neuron.vim/pull/14/files
